### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by reinhardt**
Fixes for Python 3. Instance starts; functionality not tested yet.

### CODE REVIEW

**Comment by reinhardt** [comment]
Refs #2

**Comment by ale-rt** [comment]
Ping @cekk

**Comment by cekk** [comment]
LGTM but i don't have a python3 environment where i can test it..i trust you ;)

Can you please update the changelog too, so i can release it?

**Comment by ale-rt** [comment]
> LGTM but i don't have a python3 environment where i can test it..

AFAIK that is working on production on a couple of sites since quite some time :)

> i trust you ;)

you shouldn't ;)

CC @reinhardt

**Comment by reinhardt** [comment]
I know of one production site where it's doing its job on python 3. But you shouldn't trust me either! ;-)

**Pull request merged**
